### ISSUE TITLE
Add option to present metadata on main page via properties file

### ISSUE THREAD

**Issue by kete1987** [damianszczepanik/maven-cucumber-reporting#83]
In cucumber-reporting project we can add metadata info via "Map" or via "properties file", but through maven we can only add metada info via "Map". Is it possible to add a new configuration parameter to read a properties file with metadata info?

**Comment by damianszczepanik** [comment]
I don't have plan for this but take a look at https://github.com/damianszczepanik/cucumber-reporting/pull/678 - I believe what should be done is to add support for this feature and it should not be hard as there is a code to reuse https://github.com/jenkinsci/cucumber-reports-plugin/pull/192

I will be happy to accept PR for this!

**Comment by bhreinb** [comment]
Hello @damianszczepanik 

I completely forgot about your last comment in this link 

https://github.com/jenkinsci/cucumber-reports-plugin/pull/192

It was my intention to add the feature to those other two projects you mentioned. I can have a look at adding this feature to this module if this isn't done already.

**Comment by bhreinb** [comment]
Hi @damianszczepanik 

looking at this now...I have a question though re implementation...

there is 2 ways to add json files as I see it...

```
<cucumberOutput>${project.build.directory}/cucumber.json</cucumberOutput>
 
<jsonFiles>
     <param>cucumber.json</param>
</jsonFiles>
```
The first one is to be deprecated but however still exists. Because of this code 

```
// this is deprecated but processing to keep backwards compatibility
List<String> list = new ArrayList<>();
for (File jsonFile : cucumberFiles(cucumberOutput)) {
	list.add(jsonFile.getAbsolutePath());
}

list.addAll(jsonFiles);

ReportBuilder reportBuilder = new ReportBuilder(list, configuration);


// Normally, I'd keep this private and use mocks for testing the public contract.
// I'm not sure that the author wants to get that serious with this..
static Collection<File> cucumberFiles(File file) throws MojoExecutionException {
   if (!file.exists()) {
      return Collections.emptyList();
   }
  if (file.isFile()) {
     return Arrays.asList(file);
  }
 return FileUtils.listFiles(file, new String[] {"json"}, true);
}
```
it would seem to me that we could send file "cucumber.json" within ${project.build.directory} to the report builder twice if for example that config was used. I was going to follow a similar pattern for processing classification files (i'd use the 'outputDirectory' variable rather than 'cucumberOutput') but I spotted since a list is used for processing json files, dupes potentially could be added. Does this functionality need to be revisited. I could clean this up as part of this task or implement processing classifications files slightly different to the way json files are done. Let me know your thoughts?

**Comment by damianszczepanik** [comment]
Sounds good, send PR so we can talk about the implementation :)

**Comment by bhreinb** [comment]
Hi @kete1987 

Metadata on main page via properties file is supported via the following PR https://github.com/damianszczepanik/maven-cucumber-reporting/pull/96, which will be available in the next release.

**Comment by kete1987** [comment]
@bhreinb Great!

**Comment by kathyrollo** [comment]
@kete1987 This is now addressed with the introduction of the classification files. Requesting OP to close issue. Thanks!
